# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: /dev/null ops

description: devnullops
author:
  name: /dev/null ops
  email: dbyll@ismaildemirbilek.com
  github: dbtek
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa

authors:
  aidan:
    display_name: Aidan Rowe
    nickname: aidan
    avatar: https://avatars1.githubusercontent.com/u/327286?v=3&s=75
    email: aidanrowe@gmail.com
    web: http://aidan.ro
    github: aidan-
  brian:
    display_name: Brian Sullivan
    gravatar: somethingelse
    github: bsull
    email: briansullivan@gmail.com
    avatar: https://avatars1.githubusercontent.com/u/5346367?v=3&s=75


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
